### ISSUE TITLE
invalid syntax after installing

### ISSUE THREAD

**Issue by devpascoe** [marshmallow-code/flask-marshmallow#12]
I've a vanilla Flask app. installed this package and added in my app.py
_from flask.ext.marshmallow import Marshmallow_

```
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from flask.ext.marshmallow import Marshmallow
  File "/venv/lib/python2.6/site-packages/flask/exthook.py", line 62, in load_module
    __import__(realname)
  File "/venv/lib/python2.6/site-packages/flask_marshmallow/__init__.py", line 21, in <module>
    from . import fields
  File "/venv/lib/python2.6/site-packages/flask_marshmallow/fields.py", line 115
    for key, value in iteritems(d)
      ^
SyntaxError: invalid syntax
```

Is this a python version issue? Should I be running on 3?

**Comment by sloria** [comment]
@devpascoe Flask-marshmallow does not support Python 2.6. Python >= 2.7 and >=3.3 are supported. I recommend upgrading to Python 2.7 if at all possible.

**Comment by devpascoe** [comment]
bingo 2.7
