### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by valentinoPereira** [marshmallow-code/flask-marshmallow#160]
Following is my code `test.py`
```
from flask import Flask
from wai_backend.settings import FlaskConfig
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_marshmallow import Marshmallow

app = Flask(__name__)
app.config.from_object(FlaskConfig())
db = SQLAlchemy(app)
migrate = Migrate(app)
marshmallow = Marshmallow(app)


if __name__ == "__main__":
    app.run()
```

I am getting the following error when I run `python test.py`:
```
Traceback (most recent call last):
  File "C:/Users/Ajackus/Desktop/Wai Guru/wai-api/wai_backend/test.py", line 5, in <module>
    from flask_marshmallow import Marshmallow
  File "C:\Users\Ajackus\Desktop\Wai Guru\wai-api\venv\lib\site-packages\flask_marshmallow\__init__.py", line 14, in <module>
    from marshmallow import (
  File "C:\Users\Ajackus\Desktop\Wai Guru\wai-api\venv\lib\site-packages\marshmallow\__init__.py", line 1, in <module>
    from marshmallow.schema import Schema, SchemaOpts
  File "C:\Users\Ajackus\Desktop\Wai Guru\wai-api\venv\lib\site-packages\marshmallow\schema.py", line 14, in <module>
    from marshmallow import base, fields as ma_fields, class_registry, types
  File "C:\Users\Ajackus\Desktop\Wai Guru\wai-api\venv\lib\site-packages\marshmallow\fields.py", line 14, in <module>
    from marshmallow import validate, utils, class_registry, types
  File "C:\Users\Ajackus\Desktop\Wai Guru\wai-api\venv\lib\site-packages\marshmallow\validate.py", line 355, in <module>
    class Regexp(Validator):
  File "C:\Users\Ajackus\Desktop\Wai Guru\wai-api\venv\lib\site-packages\marshmallow\validate.py", line 377, in Regexp
    error: str = None
  File "C:\Program Files\Python 3.5\lib\typing.py", line 534, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "C:\Program Files\Python 3.5\lib\typing.py", line 491, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "C:\Program Files\Python 3.5\lib\typing.py", line 491, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
TypeError: issubclass() arg 1 must be a class
```

When I comment out these two lines everything works fine:
- from flask_marshmallow import Marshmallow
- marshmallow = Marshmallow(app)

I tried googling this issue but no luck.  I am using `flask_marshmallow==0.10.1`

Can you help me with this issue please?

**Comment by sloria** [comment]
What version of Python are you using?

```
python --version
```

Early point versions of Python 3.5 have some `typing`-related bugs. It's possible the issue will be fixed by upgrading your Python version.

**Comment by sloria** [comment]
Closing this for now; feel free to comment if you're still experiencing this
