### ISSUE TITLE
return self.session.query( AttributeError: 'DummySession' object has no attribute 'query'

### ISSUE THREAD

**Issue by dani16antonio** [marshmallow-code/flask-marshmallow#168]
Hey guys, this is my first post of publication and I speak Spanish, I am very sorry if you do not understand me clearly, this is my problem
I am using flask-marshmallow in its version 0.9.0 and when I create my table if I add primary_key = True to any field that is not id (Integer) like social number I get this error (Title), and this error:

```
Traceback (most recent call last):
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask_restful\__init__.py", line 273, in error_router
    return original_handler(e)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask\_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask_restful\__init__.py", line 273, in error_router
    return original_handler(e)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask\_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask_restful\__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask\views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask_restful\__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\flask_jwt_extended\view_decorators.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\user\Documents\OverBit\Apiv2\resource\student.py", line 41, in post
    student=student_schema.load(student_data)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\marshmallow_sqlalchemy\schema.py", line 194, in load
    return super(ModelSchema, self).load(data, *args, **kwargs)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\marshmallow\schema.py", line 504, in load
    postprocess=True,
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\marshmallow\schema.py", line 640, in _do_load
    original_data=data,
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\marshmallow\schema.py", line 820, in _invoke_load_processors
    data=data, many=many, original_data=original_data,
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\marshmallow\schema.py", line 938, in _invoke_processors
    data = processor(data)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\marshmallow_sqlalchemy\schema.py", line 176, in make_instance
    instance = self.instance or self.get_instance(data)
  File "C:\Users\user\.virtualenvs\Apiv2-zDC9aQiw\lib\site-packages\marshmallow_sqlalchemy\schema.py", line 161, in get_instance
    return self.session.query(
AttributeError: 'DummySession' object has no attribute 'query'
```

this error is fixed just when my primary key is id (int)
Is there a way for my primary key to be a string?

**Comment by dani16antonio** [comment]
Yes, but I use `init_app()` method to initialize. 
I have an ”app.py” file, which initialize my API, in the bottom there are:
`db.init_app(app)
ma.init_app(app)`

Where db is a variable of another file with `db = SQLAlchemy()`, same with ma.

**Comment by sloria** [comment]
Can you post the code for the schemas and how you're loading data?

**Comment by dani16antonio** [comment]
These are some of images of my project.
If you want to watch the whole project, you can watch it here: [https://drive.google.com/file/d/1Nv6d9BOF8xZCeRBuYC1BR0yse3PEY-Gn/view?usp=sharing](url)
this is the answer I get in Udemy question:

> ey Daniel,

>Thanks for that. After some tinkering around (the project does not work out of the box due to missing Pipfile dependencies), I found the issue.

>It seems marshmallow does not support primary_key on something other than the id.

>If you move primary_key back to the id column of the StudentModel class, it works.

>I don't know exactly why that is—but it could be worth raising an issue in their GitHub repository with as much information as possible. I'm sure they would greatly appreciate it: https://github.com/marshmallow-code/marshmallow-sqlalchemy

>Kind regards,

>Jose

![1](https://user-images.githubusercontent.com/28380862/74567121-10b63080-4f43-11ea-8040-1da0813d2ee2.png)
![2](https://user-images.githubusercontent.com/28380862/74567124-114ec700-4f43-11ea-86ad-45cc8c04e557.png)
![3](https://user-images.githubusercontent.com/28380862/74567125-114ec700-4f43-11ea-9047-5b54cb82c9f3.png)
![4](https://user-images.githubusercontent.com/28380862/74567126-11e75d80-4f43-11ea-87af-c2de262bf429.png)
![5](https://user-images.githubusercontent.com/28380862/74567128-11e75d80-4f43-11ea-8af2-cf794ea3f86b.png)
![5 1](https://user-images.githubusercontent.com/28380862/74567127-11e75d80-4f43-11ea-9d64-2165825454c7.png)
![6](https://user-images.githubusercontent.com/28380862/74567129-127ff400-4f43-11ea-9d1b-c17989ee3234.png)

**Comment by sloria** [comment]
Thanks for posting that. I was not able to reproduce the issue. Non-integer primary keys should work fine.

```python
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import scoped_session, sessionmaker, relationship, backref

engine = sa.create_engine("sqlite:///:memory:")
session = scoped_session(sessionmaker(bind=engine))
Base = declarative_base()


class Author(Base):
    __tablename__ = "authors"
    id = sa.Column(sa.Integer, autoincrement=True)
    name = sa.Column(sa.String, nullable=False, unique=True, primary_key=True)

    def __repr__(self):
        return "<Author(name={self.name!r})>".format(self=self)


class Book(Base):
    __tablename__ = "books"
    id = sa.Column(sa.Integer, primary_key=True)
    title = sa.Column(sa.String)
    author_name = sa.Column(sa.String, sa.ForeignKey("authors.name"))
    author = relationship("Author", backref=backref("books"))


Base.metadata.create_all(engine)
```

```python
from marshmallow_sqlalchemy import SQLAlchemyAutoSchema, auto_field


class AuthorSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = Author
        include_relationships = True
        load_instance = True


class BookSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = Book
        include_fk = True
        include_relationships = True
        load_instance = True
```

I also verified that `ModelSchema` works.

Closing for now; will reopen if someone runs into this again

**Comment by dani16antonio** [comment]
Thank you a lot for your help.
