### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ordered' 

### ISSUE THREAD

**Issue by sjava** [marshmallow-code/flask-marshmallow#62]
Traceback (most recent call last):                                             
  File "manage.py", line 12, in <module>                                      
    from myapp.app import create_app                                           
  File "/home/zyb/myapp/myapp/app.py", line 4, in <module>                     
    from myapp import api, guanli, kanban, post, prod, public, user            
  File "/home/zyb/myapp/myapp/api/__init__.py", line 2, in <module>            
    from . import views                                                        
  File "/home/zyb/myapp/myapp/api/views.py", line 14, in <module>              
    from myapp.extensions import db, sio                                       
  File "/home/zyb/myapp/myapp/extensions.py", line 13, in <module>             
    from flask_marshmallow import Marshmallow                                  
  File "/home/zyb/.pyenv/versions/myapp/lib/python3.5/site-packages/flask_mars$
mallow/__init__.py", line 29, in <module>                                      
    from . import sqla                                                         
  File "/home/zyb/.pyenv/versions/myapp/lib/python3.5/site-packages/flask_mars$
mallow/sqla.py", line 35, in <module>                                          
    class ModelSchema(msqla.ModelSchema, Schema):                              
  File "/home/zyb/.pyenv/versions/myapp/lib/python3.5/site-packages/marshmallo$
/schema.py", line 103, in __new__                                              
    klass.opts = klass.OPTIONS_CLASS(meta, ordered=ordered)                    
TypeError: __init__() got an unexpected keyword argument 'ordered' 

**marshmallow version:3.0.0b2**

**Comment by sloria** [comment]
Looks like a compatibility bug with 3.x. I'm currently working to resolve this.

**Comment by sloria** [comment]
This is fixed in the latest release (0.8.0)
