### ISSUE TITLE
Operation not permitted when installing

### ISSUE THREAD

**Issue by mush20** [marshmallow-code/flask-marshmallow#70]
I'm trying:
pip install flask-marshmallow.

But I keep getting the following error:
Collecting flask-marshmallow
  Using cached flask_marshmallow-0.8.0-py2.py3-none-any.whl
Requirement already satisfied: marshmallow>=2.0.0 in /Library/Python/2.7/site-packages (from flask-marshmallow)
Requirement already satisfied: Flask in /Library/Python/2.7/site-packages (from flask-marshmallow)
Collecting six>=1.9.0 (from flask-marshmallow)
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied: itsdangerous>=0.21 in /Library/Python/2.7/site-packages (from Flask->flask-marshmallow)
Requirement already satisfied: Werkzeug>=0.7 in /Library/Python/2.7/site-packages (from Flask->flask-marshmallow)
Requirement already satisfied: Jinja2>=2.4 in /Library/Python/2.7/site-packages (from Flask->flask-marshmallow)
Requirement already satisfied: click>=2.0 in /Library/Python/2.7/site-packages (from Flask->flask-marshmallow)
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Python/2.7/site-packages (from Jinja2>=2.4->Flask->flask-marshmallow)
Installing collected packages: six, flask-marshmallow
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/2y/bb5jc2kn5kj0836ltx7h0jg00000gn/T/pip-Ry2d7a-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by Schabaani** [comment]
Same problem

**Comment by daaanny90** [comment]
Same error here. No Solution yet?

**Comment by daaanny90** [comment]
Solution found:

six-1.4.1 is a default pakage installed in macOS and the user is for this reason not allowed to uninstall it.

You can run: `sudo -H pip install flask-marshmallow --ignore-installed six`

**Comment by sloria** [comment]
Thanks for posting your solution @daaanny90 . This problem isn't related to flask-marshmallow, so closing.
