### ISSUE TITLE
Integration of Flask, Flask-marshmallow and MongoAlchemy

### ISSUE THREAD

**Issue by nurgasemetey** [marshmallow-code/flask-marshmallow#71]
Hello, 
I tried the following code:

```
from flask import Flask, request
from flask_mongoalchemy import MongoAlchemy
from flask_marshmallow import Marshmallow

app = Flask(__name__)
app.config['MONGOALCHEMY_DATABASE'] = 'flask-alchemy'
app.config['MONGOALCHEMY_USER'] = 'user'
app.config['MONGOALCHEMY_PASSWORD'] = 'password'
app.config['MONGOALCHEMY_SERVER_AUTH'] = False
db = MongoAlchemy(app)
ma = Marshmallow(app)

class Author(db.Document):
    name = db.StringField()

class AuthorSchema(ma.ModelSchema):
    class Meta:
        model = Author

author_schema = AuthorSchema()
authors_schema = AuthorSchema(many=True)

# mark_pilgrim = Author(name='Mark Pilgrim')
# mark_pilgrim.save()

@app.route("/author", methods=['POST'])
def addUser():
    # author = Author(name=request.json['name'])
    author_result = author_schema.load(request.json)
    author_result.data.save()
    return "OK"

@app.route("/author/<id>", methods=['GET'])
def getUser(id):
    author = Author.query.get(id)
    return author_schema.jsonify(author)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=9090)
```

But application is not starting because of following error:
```
Traceback (most recent call last):
  File "/home/nurgasemetey/IDES/pycharm-2017.2/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/nurgasemetey/IDES/pycharm-2017.2/helpers/pydev/pydevd.py", line 1023, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/media/nurgasemetey/2321222d-3af5-46b5-b8c5-824322db7a26/nurgasemetey-environment/PyCharm/PYCHARM_PROJECTS/flask-alchemy-mongo/Test.py", line 16, in <module>
    class AuthorSchema(ma.ModelSchema):
  File "/usr/local/lib/python2.7/dist-packages/marshmallow/schema.py", line 118, in __new__
    dict_cls=dict_cls
  File "/usr/local/lib/python2.7/dist-packages/marshmallow_sqlalchemy/schema.py", line 60, in get_declared_fields
    declared_fields = mcs.get_fields(converter, opts, base_fields, dict_cls)
  File "/usr/local/lib/python2.7/dist-packages/marshmallow_sqlalchemy/schema.py", line 94, in get_fields
    dict_cls=dict_cls,
  File "/usr/local/lib/python2.7/dist-packages/marshmallow_sqlalchemy/convert.py", line 93, in fields_for_model
    for prop in model.__mapper__.iterate_properties:
AttributeError: type object 'Author' has no attribute '__mapper
```

What can be wrong?

Versions

Flask==0.12
flask-marshmallow==0.8.0
Flask-MongoAlchemy==0.7.2
SQLAlchemy==1.1.11

**Comment by sloria** [comment]
`ModelSchema` only works when using flask-sqlalchemy. Flask-MongoAlchemy is not supported out of the box. You will need to use `ma.Schema` instead.

**Comment by nurgasemetey** [comment]
Thanks. I tried every possible combination but I was unsuccessful. Could you give directions?

**Comment by sloria** [comment]
@nurgasemetey Just use `ma.Schema` instead of `ma.ModelSchema`

```python
class AuthorSchema(ma.Schema):
    name = ma.String()
```

**Comment by nurgasemetey** [comment]
Thanks for this. 
I changed it but still getting this result

```python
from flask import Flask, request
from flask_mongoalchemy import MongoAlchemy
from flask_marshmallow import Marshmallow
from marshmallow import fields
from collections import namedtuple

app = Flask(__name__)
app.config['MONGOALCHEMY_DATABASE'] = 'flask-alchemy'
app.config['MONGOALCHEMY_USER'] = 'user'
app.config['MONGOALCHEMY_PASSWORD'] = 'password'
app.config['MONGOALCHEMY_SERVER_AUTH'] = False
db = MongoAlchemy(app)
ma = Marshmallow(app)

class Author(db.Document):
    name = db.StringField()

class AuthorSchema(ma.Schema):
    name = ma.String()

author_schema = AuthorSchema()
authors_schema = AuthorSchema(many=True)

# mark_pilgrim = Author(name='Mark Pilgrim')
# mark_pilgrim.save()

@app.route("/author", methods=['POST'])
def addUser():
    author = Author(name=request.json['name'])
    author_result, errors = author_schema.load(request.json)
    # author2 = namedtuple("Author", author_result.data.keys())(*author_result.data.values())
    author.save()
    # db.session.add(author_result)
    author_result.data.save()
    return "OK"

@app.route("/author/<id>", methods=['GET'])
def getUser(id):
    author = Author.query.get(id)
    return author_schema.jsonify(author)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=9090)
```

But still getting error.
```
    author_result.data.save()
AttributeError: 'dict' object has no attribute 'data'
```

I assume that marshmallow just converts to `dict`, not `Author` class. How can I accomplish this?

**Comment by sloria** [comment]
@nurgasemetey You'll need to define a `post_load` method that deserializes the data into a model instance. See https://marshmallow.readthedocs.io/en/latest/quickstart.html#deserializing-to-objects

**Comment by nurgasemetey** [comment]
@sloria Huge thanks, you're really saved me!
