### ISSUE TITLE
Validation does not raise a ValidationError

### ISSUE THREAD

**Issue by adyouri** [marshmallow-code/flask-marshmallow#75]
When serializing data using `Schema().load`, a `ValidationError` does not get raised; instead, I get an `UnmarshalResult` object with the `data` and `errors`. Is this the expected output? does flask-marshmallow not raise a `ValidationError` when there are errors in the submitted data?

Example:

```
>>> from project.schemas import TermSchema
>>> term_schema = TermSchema()
>>> term_data = dict(term=None)
>>> term_schema.load(term_data)
UnmarshalResult(data={}, errors={'term': ['Field may not be null.']})
```

Why is it returning an `UnmarshalResult` object instead of raising a validation error?

Here is the `schemas.py`:

```
from marshmallow import post_load
from project.models import Term, Translation
from flask_marshmallow import Marshmallow
from marshmallow_sqlalchemy import field_for

ma = Marshmallow()

class TranslationSchema(ma.ModelSchema):
    class Meta:
        model = Translation

class TermSchema(ma.ModelSchema):
    term = field_for(Term, 'term', required=True)

    class Meta:
        model = Term
    translations = ma.Nested(TranslationSchema, many=True)

    # Validate term is not none
    # Validate full_term is not none if is_acronym
    @post_load
    def make_term(self, data):
        return data
```

**Comment by bustawin** [comment]
You need to install marshmallow 3.0 for that (from Marshmallow website):
```bash
pip install -U marshmallow --pre
```
Notice the `--pre`.

**Comment by oubeichen** [comment]
@bustawin There is another exception after upgrading marshmallow to 3.0.
```Traceback (most recent call last):
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/sso_auth_drf/flask/auth.py", line 29, in decorator
    return func(*args, **kwargs)
  File "/Users/oubeichen/Projects/trial-lesson/trial_lesson/lesson/views.py", line 68, in create_lesson
    resp = LessonSerializer().jsonify(instance)
  File "/Users/oubeichen/.virtualenvs/trial-lesson/lib/python3.6/site-packages/flask_marshmallow/schema.py", line 35, in jsonify
    data = self.dump(obj, many=many).data
AttributeError: 'dict' object has no attribute 'data'
```

**Comment by adyouri** [comment]
@oubeichen You are trying to access the `data` attribute on a dictionary where it doesn't exist. What exactly are you trying to do? Please provide the code that causes the error.

**Comment by oubeichen** [comment]
@adyouri 
I just called
`SomeSerializer().jsonify(obj)`
`SomeSerializer` is a instance of `Marshmallow().ModelSchema`
and the `obj` is a instance of `SQLAlchemy().model` from database.

**Comment by CristianoYL** [comment]
@oubeichen I think marshmallow 3.0 has a major change in their return format. The `dump()` method returns the data straight away, you no longer need to call `.data` on it.

**Comment by ashwani99** [comment]
Hey @adyouri ! Just a quick question, how did you manage to write custom validation/use in-built validation for `TestSchema`? I am not sure if `flask-marshmallow` is supported to use `ValidationError` from `marshmallow`

From your snippet, I am pasting a part.

```python
class TermSchema(ma.ModelSchema):
    term = field_for(Term, 'term', required=True)

    class Meta:
        model = Term
    translations = ma.Nested(TranslationSchema, many=True)

    # Please expand the commented part
    # Validate term is not none
    # Validate full_term is not none if is_acronym

    @post_load
    def make_term(self, data):
        return data
```

**Comment by rshah88** [comment]
Hey, 
When is 3,0 releasing?

**Comment by sloria** [comment]
Closing this issue, as the behavior described in the OP is expected in marshmallow 2. In marshmallow 2 with `strict = False`, an `UnmarshalResult` is returned. `strict = False` will cause a `ValidationError` to be raised.

In marshmallow 3, a `ValidationError` is always raised if validation fails: https://marshmallow.readthedocs.io/en/latest/upgrading.html#schemas-are-always-strict .

As for the marshmallow 3 release date, we can't make any promises about a release date, but you can follow the milestone here: https://github.com/marshmallow-code/marshmallow/milestone/10 . At this point, it's stable enough that we're recommending it for new projects.

**Comment by Sankepy** [comment]
Hey, I am facing the same issue, what am I doing wrong?

```python
    def post(self):
        print(request.get_json())
        try:
            result = UserSchema().load(**request.get_json())
            print(result)
            new_user = User(**result)
            db.session.add(new_user)
            db.session.commit()
            return user_schema.jsonify(new_user)
        except ValidationError as error:
            print(error.message)
            print(error.valid_data)
            return error.message
```


my schema:

```python
class UserSchema(ma.Schema):
    class Meta:
        fields = ('id', 'first_name', 'last_name', 'user_type', 'role', 'notification', 'created_at', 'updated_at')
```

**Comment by sloria** [comment]
`**request.get_json()` doesn't look right. `load` takes an input dictionary as an argument, and you are passing the data as kwargs. Is that the issue?

**Comment by snake-py** [comment]
@sloria Yes it seems this was indeed the issue. Thank you!
